### SQLITE

In [1]:
# Create a table employee with attributes eid, name, addr, desig and salary. Ins
# details of 5 employees and fetch all the employees whose salary is greater tha
import sqlite3
conn = sqlite3.connect('example.db')
cursor = conn.cursor()
# Create table
cursor.execute('''CREATE TABLE IF NOT EXISTS employee
 (eid INTEGER, name TEXT, addr TEXT, desig TEXT, salary REAL)''')
# Insert employee details
employees = [
 (1, 'Alice', 'New York', 'Manager', 60000),
 (2, 'Bob', 'California', 'Developer', 55000),
 (3, 'Charlie', 'Texas', 'Analyst', 48000),
 (4, 'Daisy', 'Nevada', 'Consultant', 52000),
 (5, 'Eve', 'Florida', 'Engineer', 75000),
]
cursor.executemany("INSERT INTO employee VALUES (?, ?, ?, ?, ?)", employees)
conn.commit()
# Fetch employees with salary > 50000
cursor.execute("SELECT * FROM employee WHERE salary > 50000")
high_salary_employees = cursor.fetchall()
for emp in high_salary_employees:
 print(emp)
conn.close()

(1, 'Alice', 'New York', 'Manager', 60000.0)
(2, 'Bob', 'California', 'Developer', 55000.0)
(4, 'Daisy', 'Nevada', 'Consultant', 52000.0)
(5, 'Eve', 'Florida', 'Engineer', 75000.0)


In [2]:
# 3. Consider the employee table and fetch employee name and designation.
conn = sqlite3.connect('example.db')
cursor = conn.cursor()
cursor.execute("SELECT name, desig FROM employee")
rows = cursor.fetchall()
for row in rows:
 print(row)
conn.close()


('Alice', 'Manager')
('Bob', 'Developer')
('Charlie', 'Analyst')
('Daisy', 'Consultant')
('Eve', 'Engineer')


In [ ]:
# 1. Write a Python program to delete a specific row from a given SQLite table.

import sqlite3

def delete_row(db_name, table_name, column_name, value):
    valid_tables = ['employees']  # Valid table names (updated to 'employees')
    valid_columns = ['emp_no']  # Valid column names (updated to 'emp_no')

    # Check if the table and column are valid
    if table_name not in valid_tables:
        print(f"Error: Invalid table name '{table_name}'.")
        return
    if column_name not in valid_columns:
        print(f"Error: Invalid column name '{column_name}'.")
        return

    try:
        # Open SQLite connection with a timeout to retry if the database is locked
        conn = sqlite3.connect(db_name, timeout=10)  # Timeout set to 10 seconds
        cursor = conn.cursor()

        # Create the DELETE SQL query using parameterized values
        query = f"DELETE FROM {table_name} WHERE {column_name} = ?"
        cursor.execute(query, (value,))  # Parameterized query to prevent SQL injection
        
        # Commit the changes
        conn.commit()

        # Check if the row was deleted
        if cursor.rowcount > 0:
            print(f"Row(s) deleted where {column_name} = {value}.")
        else:
            print(f"No row found with {column_name} = {value}.")

    except sqlite3.Error as e:
        print(f"An error occurred: {e}")
    finally:
        cursor.close()
        conn.close()

# Example usage
if __name__ == "__main__":
    # Update the following to reflect the new data
    db_name = 'employees_db-full-1.0.6.db'  # SQLite database name
    table_name = 'employees'  # Table name
    column_name = 'emp_no'  # Column name to filter by (employee number)
    value = 499999  # Value to match (employee number)

    # Call the function to delete the row
    delete_row(db_name, table_name, column_name, value)


In [ ]:
# 3. Consider the employee table and fetch employee name and hire date.

conn = sqlite3.connect('employees_db-full-1.0.6.db')
cursor = conn.cursor()

# Query to fetch employee name and designation
query = "SELECT first_name, hire_date FROM employees"

# Execute the query
cursor.execute(query)

# Fetch all the results
employees = cursor.fetchall()

# Print the results
for emp in employees:
    print(f"Employee Name: {emp[0]}, Hire Date: {emp[1]}")

# Close the connection
conn.close()

In [ ]:
''' 4. Create a table employee with attributes eid, name, addr, desig and salary. Insert
details of 5 employees and fetch all the employees whose salary is greater than 50000.'''

import sqlite3

conn = sqlite3.connect('employee.db')  # Create a new database file 'employee.db'
cursor = conn.cursor()

create_table_query = """
CREATE TABLE IF NOT EXISTS employee (
    eid INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    addr TEXT,
    desig TEXT,
    salary REAL
);
"""
cursor.execute(create_table_query)


insert_employees_query = """
INSERT INTO employee (eid, name, addr, desig, salary)
VALUES
(1, 'John Doe', '123 Elm St', 'Software Engineer', 60000),
(2, 'Jane Smith', '456 Oak Ave', 'Project Manager', 70000),
(3, 'Alice Johnson', '789 Pine Rd', 'Data Analyst', 45000),
(4, 'Bob Brown', '101 Maple Dr', 'HR Specialist', 55000),
(5, 'Charlie Davis', '202 Birch Blvd', 'Senior Developer', 80000);
"""

cursor.execute("SELECT COUNT(*) FROM employee")
if cursor.fetchone()[0] == 0:  # If no records are present
    cursor.executescript(insert_employees_query)


fetch_query = "SELECT * FROM employee WHERE salary > 50000"
cursor.execute(fetch_query)

employees = cursor.fetchall()
for emp in employees:
    print(f"EID: {emp[0]}, Name: {emp[1]}, Address: {emp[2]}, Designation: {emp[3]}, Salary: {emp[4]}")

conn.commit()  # Commit any changes (not needed for SELECT but good practice)
conn.close()


### Numpy

In [1]:
# 1. Calculate average values of two given arrays.

import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
average = (array1 + array2) / 2
print(average)


[2.5 3.5 4.5]


In [ ]:
# 1. Calculate average values of two given arrays.
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 15, 25, 35, 45])

# Calculate the average of each array
avg_arr1 = np.mean(arr1)
avg_arr2 = np.mean(arr2)

# Print the average values
print(f"Average of arr1: {avg_arr1}")
print(f"Average of arr2: {avg_arr2}")

# Optionally, calculate the overall average of both arrays combined
combined_avg = np.mean(np.concatenate((arr1, arr2)))
print(f"Average of both arrays combined: {combined_avg}")

In [3]:
# 2. Compare two arrays.
import numpy as np

# Define two sample arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([10, 25, 30, 40, 50])

element_comparison = []
for i in range(len(arr1)):
    element_comparison.append(arr1[i] == arr2[i])
    
arr_identical = True
if len(arr1) != len(arr2):
    arr_identical = False
else:
    for i in range(len(arr1)):
        if arr1[i] != arr2[i]:
            arr_identical = False
            break

print("Is array identical: ", arr_identical)

Is array identical:  False


In [4]:
# 3. Reverse an array.

array = np.array([10, 20, 30, 40, 50])

reversed_array = array[::-1]
print("Reversed array:", reversed_array)


Reversed array: [50 40 30 20 10]


In [6]:
# 4. Sort the values in a matrix.

matrix = np.array([[34, 1, 23],
                   [4, 3, 15],
                   [5, 12, 19]])

print("Original matrix:")
print(matrix)

sorted_matrix = np.sort(matrix, axis=None).reshape(matrix.shape)

print("\nSorted matrix:")
print(sorted_matrix)



Original matrix:
[[34  1 23]
 [ 4  3 15]
 [ 5 12 19]]

Sorted matrix:
[[ 1  3  4]
 [ 5 12 15]
 [19 23 34]]
